/**
 * Seed list of NYC restaurants to track.
 *
 * Each restaurant needs:
 *   - cuisines: 1-2 cuisine tags (used as filter chips on occasion pages)
 *   - occasions: 1-4 occasion tags (which leaderboards it appears on)
 *   - price_tier: $, $$, $$$, or $$$$
 *
 * Curation philosophy:
 *   - 6 occasions × ~12-15 restaurants each = ~70 unique restaurants with overlap
 *   - 11 cuisines × at least 4-5 spots per cuisine for filter usefulness
 *   - Mix of TikTok-viral spots (expected: overrated) and locals' picks (expected: underrated)
 *   - Price tier auto-qualifies for "Under $25" (any restaurant with price_tier='$')
 *
 * This is a starting curation. Edit freely and re-run `npm run seed` to sync.
 *
 * NOTE: A restaurant with price_tier='$' is automatically added to "under-25"
 * even if not explicitly tagged. The pipeline handles that.
 */

import type { Borough, Cuisine, Occasion, PriceTier } from "./types";

export type SeedRestaurant = {
  slug: string;
  name: string;
  neighborhood: string;
  borough: Borough;
  search_terms: string[];
  cuisines: Cuisine[];
  occasions: Occasion[];
  price_tier: PriceTier;
  notes?: string;
};

export const SEED_RESTAURANTS: SeedRestaurant[] = [
  // ===========================================================
  // ITALIAN — date night + group dinner heavy
  // ===========================================================
  {
    slug: "carbone",
    name: "Carbone",
    neighborhood: "Greenwich Village",
    borough: "manhattan",
    search_terms: ["carbone nyc", "spicy rigatoni vodka"],
    cuisines: ["italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
    notes: "Spicy rigatoni hype machine.",
  },
  {
    slug: "don-angie",
    name: "Don Angie",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["don angie", "lasagna pinwheels"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Pinwheel lasagna. Six-week reservation.",
  },
  {
    slug: "torrisi",
    name: "Torrisi",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["torrisi nyc", "torrisi bar restaurant"],
    cuisines: ["italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
  },
  {
    slug: "saint-theos",
    name: "Saint Theo's",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["saint theos", "saint theo's nyc"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
  },
  {
    slug: "via-carota",
    name: "Via Carota",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["via carota", "via carota cacio e pepe"],
    cuisines: ["italian"],
    occasions: ["date-night", "solo-dining"],
    price_tier: "$$$",
    notes: "No-reservations. Two-hour wait normal.",
  },
  {
    slug: "raouls",
    name: "Raoul's",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["raouls", "raoul's au poivre burger"],
    cuisines: ["french"],
    occasions: ["date-night", "late-night"],
    price_tier: "$$$",
    notes: "The au poivre burger. Bar-only.",
  },
  {
    slug: "i-sodi",
    name: "I Sodi",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["i sodi", "i sodi nyc", "lasagna i sodi"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Tuscan, intimate, hard-to-book. Quiet excellence.",
  },
  {
    slug: "rezdora",
    name: "Rezdôra",
    neighborhood: "Flatiron",
    borough: "manhattan",
    search_terms: ["rezdora", "rezdora nyc", "emilia romagna pasta"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
  },
  {
    slug: "lilia",
    name: "Lilia",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["lilia williamsburg", "lilia missy robbins"],
    cuisines: ["italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
  },
  {
    slug: "misi",
    name: "Misi",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["misi nyc", "misi pasta", "missy robbins misi"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
  },

  // ===========================================================
  // PIZZA — late night + under $25 + solo
  // ===========================================================
  {
    slug: "lucali",
    name: "Lucali",
    neighborhood: "Carroll Gardens",
    borough: "brooklyn",
    search_terms: ["lucali", "lucali pizza brooklyn"],
    cuisines: ["pizza", "italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "BYOB pizza. Four-hour wait is the experience.",
  },
  {
    slug: "joes-pizza",
    name: "Joe's Pizza",
    neighborhood: "Greenwich Village",
    borough: "manhattan",
    search_terms: ["joes pizza nyc", "joe's pizza carmine"],
    cuisines: ["pizza"],
    occasions: ["late-night", "under-25", "solo-dining"],
    price_tier: "$",
  },
  {
    slug: "scarrs-pizza",
    name: "Scarr's Pizza",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["scarrs pizza", "scarrs nyc", "scarr's lower east side"],
    cuisines: ["pizza"],
    occasions: ["late-night", "under-25", "solo-dining"],
    price_tier: "$",
  },
  {
    slug: "lartusi",
    name: "L'Artusi",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["lartusi", "l'artusi west village"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
  },
  {
    slug: "rubirosa",
    name: "Rubirosa",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["rubirosa", "rubirosa tie dye pizza"],
    cuisines: ["pizza", "italian"],
    occasions: ["group-dinner", "date-night"],
    price_tier: "$$",
    notes: "The tie-dye pizza is the entire Instagram caption.",
  },
  {
    slug: "prince-st-pizza",
    name: "Prince Street Pizza",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["prince street pizza", "prince st pizza spicy spring"],
    cuisines: ["pizza"],
    occasions: ["under-25", "solo-dining", "late-night"],
    price_tier: "$",
  },

  // ===========================================================
  // KOREAN
  // ===========================================================
  {
    slug: "cote",
    name: "COTE",
    neighborhood: "Flatiron",
    borough: "manhattan",
    search_terms: ["cote korean steakhouse", "cote nyc"],
    cuisines: ["korean"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
    notes: "Korean steakhouse. Has Miami and Vegas locations now.",
  },
  {
    slug: "atomix",
    name: "Atomix",
    neighborhood: "NoMad",
    borough: "manhattan",
    search_terms: ["atomix", "atomix korean", "atomix nyc"],
    cuisines: ["korean"],
    occasions: ["date-night"],
    price_tier: "$$$$",
    notes: "Korean tasting menu. 2 Michelin stars.",
  },
  {
    slug: "kochi",
    name: "Kochi",
    neighborhood: "Hell's Kitchen",
    borough: "manhattan",
    search_terms: ["kochi nyc", "kochi korean tasting menu"],
    cuisines: ["korean"],
    occasions: ["date-night"],
    price_tier: "$$$",
  },
  {
    slug: "her-name-is-han",
    name: "Her Name Is Han",
    neighborhood: "Koreatown",
    borough: "manhattan",
    search_terms: ["her name is han", "her name is han ktown"],
    cuisines: ["korean"],
    occasions: ["group-dinner"],
    price_tier: "$$",
  },
  {
    slug: "sik-gaek",
    name: "Sik Gaek",
    neighborhood: "Flushing",
    borough: "queens",
    search_terms: ["sik gaek flushing", "sik gaek queens", "live octopus"],
    cuisines: ["korean"],
    occasions: ["group-dinner", "late-night"],
    price_tier: "$$",
    notes: "Live octopus, Soju nights. Locals love it.",
  },

  // ===========================================================
  // JAPANESE
  // ===========================================================
  {
    slug: "sushi-nakazawa",
    name: "Sushi Nakazawa",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["sushi nakazawa", "nakazawa omakase"],
    cuisines: ["japanese"],
    occasions: ["date-night", "solo-dining"],
    price_tier: "$$$$",
  },
  {
    slug: "sushi-noz",
    name: "Sushi Noz",
    neighborhood: "Upper East Side",
    borough: "manhattan",
    search_terms: ["sushi noz", "sushi noz upper east side"],
    cuisines: ["japanese"],
    occasions: ["date-night", "solo-dining"],
    price_tier: "$$$$",
  },
  {
    slug: "tomoe-sushi",
    name: "Tomoe Sushi",
    neighborhood: "Greenwich Village",
    borough: "manhattan",
    search_terms: ["tomoe sushi", "tomoe nyc"],
    cuisines: ["japanese"],
    occasions: ["solo-dining", "date-night"],
    price_tier: "$$",
    notes: "Cash only. Locals know.",
  },
  {
    slug: "ootoya-chelsea",
    name: "Ootoya",
    neighborhood: "Chelsea",
    borough: "manhattan",
    search_terms: ["ootoya nyc", "ootoya chelsea"],
    cuisines: ["japanese"],
    occasions: ["solo-dining", "under-25"],
    price_tier: "$$",
  },
  {
    slug: "ippudo",
    name: "Ippudo",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["ippudo nyc", "ippudo ramen"],
    cuisines: ["japanese"],
    occasions: ["solo-dining", "late-night"],
    price_tier: "$$",
  },
  {
    slug: "ichiran",
    name: "Ichiran",
    neighborhood: "Bushwick",
    borough: "brooklyn",
    search_terms: ["ichiran ramen", "ichiran brooklyn"],
    cuisines: ["japanese"],
    occasions: ["solo-dining", "late-night"],
    price_tier: "$$",
    notes: "The solo booth ramen experience.",
  },

  // ===========================================================
  // CHINESE
  // ===========================================================
  {
    slug: "wus-wonton-king",
    name: "Wu's Wonton King",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["wus wonton king", "wonton king nyc"],
    cuisines: ["chinese"],
    occasions: ["group-dinner", "under-25"],
    price_tier: "$$",
    notes: "BYOB Cantonese. Locals know.",
  },
  {
    slug: "cafe-china",
    name: "Cafe China",
    neighborhood: "Midtown",
    borough: "manhattan",
    search_terms: ["cafe china nyc", "cafe china sichuan"],
    cuisines: ["chinese"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "Sichuan. Quietly a real one.",
  },
  {
    slug: "joes-shanghai",
    name: "Joe's Shanghai",
    neighborhood: "Flushing",
    borough: "queens",
    search_terms: ["joes shanghai", "soup dumplings nyc"],
    cuisines: ["chinese"],
    occasions: ["group-dinner", "under-25"],
    price_tier: "$$",
  },
  {
    slug: "bonnies",
    name: "Bonnie's",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["bonnies williamsburg", "bonnies cantonese"],
    cuisines: ["chinese"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Cantonese-American. TikTok favorite.",
  },
  {
    slug: "ho-foods",
    name: "Ho Foods",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["ho foods nyc", "beef noodle soup ho foods"],
    cuisines: ["chinese"],
    occasions: ["solo-dining", "under-25"],
    price_tier: "$$",
    notes: "Taiwanese beef noodle. Quiet excellence.",
  },
  {
    slug: "nan-xiang",
    name: "Nan Xiang Xiao Long Bao",
    neighborhood: "Flushing",
    borough: "queens",
    search_terms: ["nan xiang xiao long bao", "nan xiang flushing"],
    cuisines: ["chinese"],
    occasions: ["group-dinner", "under-25"],
    price_tier: "$",
  },

  // ===========================================================
  // INDIAN
  // ===========================================================
  {
    slug: "ambassadors-clubhouse",
    name: "Ambassador's Clubhouse",
    neighborhood: "NoMad",
    borough: "manhattan",
    search_terms: ["ambassadors clubhouse", "punjabi nyc"],
    cuisines: ["indian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Currently the most impossible reservation.",
  },
  {
    slug: "semma",
    name: "Semma",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["semma nyc", "semma south indian"],
    cuisines: ["indian"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Michelin-starred South Indian. Earned it.",
  },
  {
    slug: "dhamaka",
    name: "Dhamaka",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["dhamaka nyc", "dhamaka lower east side"],
    cuisines: ["indian"],
    occasions: ["group-dinner"],
    price_tier: "$$$",
  },
  {
    slug: "adda",
    name: "Adda",
    neighborhood: "Long Island City",
    borough: "queens",
    search_terms: ["adda nyc", "adda lic", "adda indian"],
    cuisines: ["indian"],
    occasions: ["group-dinner"],
    price_tier: "$$",
    notes: "Unfiltered Indian. Locals love.",
  },
  {
    slug: "junoon",
    name: "Junoon",
    neighborhood: "Flatiron",
    borough: "manhattan",
    search_terms: ["junoon nyc", "junoon flatiron"],
    cuisines: ["indian"],
    occasions: ["date-night"],
    price_tier: "$$$$",
  },

  // ===========================================================
  // MEXICAN
  // ===========================================================
  {
    slug: "cosme",
    name: "Cosme",
    neighborhood: "Flatiron",
    borough: "manhattan",
    search_terms: ["cosme nyc", "cosme husk meringue"],
    cuisines: ["mexican"],
    occasions: ["date-night"],
    price_tier: "$$$$",
    notes: "Husk meringue is the Instagram caption.",
  },
  {
    slug: "casa-enrique",
    name: "Casa Enrique",
    neighborhood: "Long Island City",
    borough: "queens",
    search_terms: ["casa enrique", "casa enrique lic"],
    cuisines: ["mexican"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "Michelin Mexican in LIC. Local secret.",
  },
  {
    slug: "tacombi",
    name: "Tacombi",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["tacombi nyc", "tacombi nolita"],
    cuisines: ["mexican"],
    occasions: ["under-25", "brunch"],
    price_tier: "$$",
  },
  {
    slug: "los-tacos-no1",
    name: "Los Tacos No. 1",
    neighborhood: "Chelsea Market",
    borough: "manhattan",
    search_terms: ["los tacos no 1", "los tacos chelsea market"],
    cuisines: ["mexican"],
    occasions: ["under-25", "solo-dining", "late-night"],
    price_tier: "$",
  },
  {
    slug: "oxomoco",
    name: "Oxomoco",
    neighborhood: "Greenpoint",
    borough: "brooklyn",
    search_terms: ["oxomoco brooklyn", "oxomoco greenpoint"],
    cuisines: ["mexican"],
    occasions: ["date-night", "brunch"],
    price_tier: "$$$",
  },

  // ===========================================================
  // FRENCH
  // ===========================================================
  {
    slug: "le-bernardin",
    name: "Le Bernardin",
    neighborhood: "Midtown",
    borough: "manhattan",
    search_terms: ["le bernardin", "ripert le bernardin"],
    cuisines: ["french"],
    occasions: ["date-night"],
    price_tier: "$$$$",
  },
  {
    slug: "le-coucou",
    name: "Le Coucou",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["le coucou nyc", "le coucou soho"],
    cuisines: ["french"],
    occasions: ["date-night"],
    price_tier: "$$$$",
  },
  {
    slug: "frenchette",
    name: "Frenchette",
    neighborhood: "TriBeCa",
    borough: "manhattan",
    search_terms: ["frenchette tribeca", "frenchette nyc"],
    cuisines: ["french"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
  },
  {
    slug: "buvette",
    name: "Buvette",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["buvette nyc", "buvette west village brunch"],
    cuisines: ["french"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
  },
  {
    slug: "balthazar",
    name: "Balthazar",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["balthazar nyc", "balthazar brunch soho"],
    cuisines: ["french"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
  },

  // ===========================================================
  // THAI
  // ===========================================================
  {
    slug: "fish-cheeks",
    name: "Fish Cheeks",
    neighborhood: "NoHo",
    borough: "manhattan",
    search_terms: ["fish cheeks nyc", "fish cheeks thai"],
    cuisines: ["thai"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
  },
  {
    slug: "uncle-boons-sister",
    name: "Thai Diner",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["thai diner nyc", "thai diner nolita"],
    cuisines: ["thai"],
    occasions: ["brunch", "group-dinner"],
    price_tier: "$$",
  },
  {
    slug: "sripraphai",
    name: "SriPraPhai",
    neighborhood: "Woodside",
    borough: "queens",
    search_terms: ["sripraphai", "sripraphai woodside thai"],
    cuisines: ["thai"],
    occasions: ["group-dinner", "under-25"],
    price_tier: "$$",
    notes: "The locals' Thai. Real heat.",
  },
  {
    slug: "soothr",
    name: "Soothr",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["soothr nyc", "soothr east village"],
    cuisines: ["thai"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
  },

  // ===========================================================
  // MEDITERRANEAN
  // ===========================================================
  {
    slug: "cafe-mogador",
    name: "Cafe Mogador",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["cafe mogador", "mogador brunch"],
    cuisines: ["mediterranean"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$",
    notes: "Moroccan brunch institution.",
  },
  {
    slug: "miss-ada",
    name: "Miss Ada",
    neighborhood: "Fort Greene",
    borough: "brooklyn",
    search_terms: ["miss ada brooklyn", "miss ada fort greene"],
    cuisines: ["mediterranean"],
    occasions: ["date-night", "brunch"],
    price_tier: "$$$",
  },
  {
    slug: "eyval",
    name: "Eyval",
    neighborhood: "Bushwick",
    borough: "brooklyn",
    search_terms: ["eyval bushwick", "eyval persian"],
    cuisines: ["mediterranean"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Persian. Earned every star without TikTok.",
  },
  {
    slug: "shukette",
    name: "Shukette",
    neighborhood: "Chelsea",
    borough: "manhattan",
    search_terms: ["shukette nyc", "shukette chelsea"],
    cuisines: ["mediterranean"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
  },
  {
    slug: "12-chairs",
    name: "12 Chairs Café",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["12 chairs cafe soho", "12 chairs israeli"],
    cuisines: ["mediterranean"],
    occasions: ["brunch", "solo-dining"],
    price_tier: "$$",
  },

  // ===========================================================
  // AMERICAN — burgers, brunch, classics
  // ===========================================================
  {
    slug: "polo-bar",
    name: "The Polo Bar",
    neighborhood: "Midtown East",
    borough: "manhattan",
    search_terms: ["polo bar", "ralph lauren polo bar"],
    cuisines: ["american"],
    occasions: ["date-night"],
    price_tier: "$$$$",
    notes: "Six-month wait for non-celebs.",
  },
  {
    slug: "eighty-six",
    name: "The Eighty-Six",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["the eighty-six", "the eighty six nyc"],
    cuisines: ["american"],
    occasions: ["date-night", "late-night"],
    price_tier: "$$$",
    notes: "Members-only-feeling.",
  },
  {
    slug: "tatiana",
    name: "Tatiana",
    neighborhood: "Lincoln Square",
    borough: "manhattan",
    search_terms: ["tatiana kwame", "tatiana lincoln center"],
    cuisines: ["american"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
    notes: "Kwame Onwuachi.",
  },
  {
    slug: "mels",
    name: "Mel's",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["mels nyc", "mel's soho", "mels burger"],
    cuisines: ["american"],
    occasions: ["brunch", "late-night"],
    price_tier: "$$$",
    notes: "The cheeseburger is the Instagram caption.",
  },
  {
    slug: "jacks-wife-freda",
    name: "Jack's Wife Freda",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["jacks wife freda", "green shakshuka"],
    cuisines: ["mediterranean", "american"],
    occasions: ["brunch"],
    price_tier: "$$",
    notes: "Green shakshuka.",
  },
  {
    slug: "russ-and-daughters",
    name: "Russ & Daughters Cafe",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["russ and daughters", "russ daughters cafe"],
    cuisines: ["american"],
    occasions: ["brunch"],
    price_tier: "$$",
  },
  {
    slug: "katzs",
    name: "Katz's Delicatessen",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["katzs deli", "katz's pastrami"],
    cuisines: ["american"],
    occasions: ["solo-dining", "late-night", "under-25"],
    price_tier: "$$",
  },
  {
    slug: "veselka",
    name: "Veselka",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["veselka", "veselka pierogi"],
    cuisines: ["american"],
    occasions: ["late-night", "brunch", "under-25"],
    price_tier: "$$",
    notes: "Ukrainian classic. Real institution.",
  },
  {
    slug: "diner",
    name: "Diner",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["diner williamsburg", "diner brooklyn"],
    cuisines: ["american"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
  },
  {
    slug: "four-horsemen",
    name: "Four Horsemen",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["four horsemen", "four horsemen wine bar"],
    cuisines: ["american"],
    occasions: ["date-night", "solo-dining"],
    price_tier: "$$$",
    notes: "Natural wine + small plates. James Murphy's spot.",
  },
  {
    slug: "cervos",
    name: "Cervo's",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["cervos nyc", "cervo's"],
    cuisines: ["mediterranean"],
    occasions: ["date-night", "solo-dining"],
    price_tier: "$$$",
  },
  {
    slug: "llama-san",
    name: "Llama San",
    neighborhood: "Greenwich Village",
    borough: "manhattan",
    search_terms: ["llama san nyc", "llama san peruvian"],
    cuisines: ["japanese"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Peruvian-Japanese (Nikkei).",
  },

  // ===========================================================
  // BRUNCH heavy-hitters
  // ===========================================================
  {
    slug: "clinton-st-baking",
    name: "Clinton St. Baking Company",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["clinton street baking", "clinton st pancakes"],
    cuisines: ["american"],
    occasions: ["brunch"],
    price_tier: "$$",
    notes: "The blueberry pancake hype machine.",
  },
  {
    slug: "sadelles",
    name: "Sadelle's",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["sadelles soho", "sadelles brunch"],
    cuisines: ["american"],
    occasions: ["brunch"],
    price_tier: "$$$",
  },
  {
    slug: "egg-shop",
    name: "Egg Shop",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["egg shop nolita", "egg shop nyc"],
    cuisines: ["american"],
    occasions: ["brunch"],
    price_tier: "$$",
  },

  // ===========================================================
  // LATE NIGHT extras
  // ===========================================================
  {
    slug: "wo-hop",
    name: "Wo Hop",
    neighborhood: "Chinatown",
    borough: "manhattan",
    search_terms: ["wo hop chinatown", "wo hop late night"],
    cuisines: ["chinese"],
    occasions: ["late-night", "under-25"],
    price_tier: "$",
    notes: "Open till 4am. The drunk meal.",
  },
  {
    slug: "frenchman",
    name: "The Frenchman's",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["the frenchmans nyc", "frenchmans east village"],
    cuisines: ["french"],
    occasions: ["late-night", "date-night"],
    price_tier: "$$$",
  },

  // ===========================================================
  // UNDER $25 extras
  // ===========================================================
  {
    slug: "xian-famous",
    name: "Xi'an Famous Foods",
    neighborhood: "Multiple",
    borough: "manhattan",
    search_terms: ["xian famous foods", "xian biang biang noodles"],
    cuisines: ["chinese"],
    occasions: ["under-25", "solo-dining"],
    price_tier: "$",
  },
  {
    slug: "punjabi-deli",
    name: "Punjabi Grocery & Deli",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["punjabi grocery deli", "punjabi deli east village"],
    cuisines: ["indian"],
    occasions: ["under-25", "late-night", "solo-dining"],
    price_tier: "$",
    notes: "Cheapest dal in Manhattan. Open 24/7.",
  },
  {
    slug: "vanessas-dumplings",
    name: "Vanessa's Dumpling House",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["vanessas dumplings", "vanessa dumpling house"],
    cuisines: ["chinese"],
    occasions: ["under-25", "solo-dining"],
    price_tier: "$",
  },
];
