/**
 * Seed list of NYC restaurants to track.
 *
 * Each restaurant needs:
 *   - cuisines: 1-2 cuisine tags (used as filter chips on occasion pages)
 *   - occasions: 1-4 occasion tags (which leaderboards it appears on)
 *   - price_tier: $, $$, $$$, or $$$$
 *
 * Curation philosophy:
 *   - 6 occasions × ~12-15 restaurants each = ~70 unique restaurants with overlap
 *   - 11 cuisines × at least 4-5 spots per cuisine for filter usefulness
 *   - Mix of TikTok-viral spots (expected: overrated) and locals' picks (expected: underrated)
 *   - Price tier auto-qualifies for "Under $25" (any restaurant with price_tier='$')
 *
 * This is a starting curation. Edit freely and re-run `npm run seed` to sync.
 *
 * NOTE: A restaurant with price_tier='$' is automatically added to "under-25"
 * even if not explicitly tagged. The pipeline handles that.
 */

import type { Borough, Cuisine, Occasion, PriceTier } from "./types";

export type SeedRestaurant = {
  slug: string;
  name: string;
  neighborhood: string;
  borough: Borough;
  search_terms: string[];
  cuisines: Cuisine[];
  occasions: Occasion[];
  price_tier: PriceTier;
  notes?: string;
};

export const SEED_RESTAURANTS: SeedRestaurant[] = [
  // ===========================================================
  // ITALIAN — date night + group dinner heavy
  // ===========================================================
  {
    slug: "carbone",
    name: "Carbone",
    neighborhood: "Greenwich Village",
    borough: "manhattan",
    search_terms: ["carbone nyc", "spicy rigatoni vodka"],
    cuisines: ["italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
    notes: "Spicy rigatoni hype machine.",
  },
  {
    slug: "don-angie",
    name: "Don Angie",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["don angie", "lasagna pinwheels"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Pinwheel lasagna. Six-week reservation.",
  },
  {
    slug: "torrisi",
    name: "Torrisi",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["torrisi nyc", "torrisi bar restaurant"],
    cuisines: ["italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
  },
  {
    slug: "saint-theos",
    name: "Saint Theo's",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["saint theos", "saint theo's nyc"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
  },
  {
    slug: "via-carota",
    name: "Via Carota",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["via carota", "via carota cacio e pepe"],
    cuisines: ["italian"],
    occasions: ["date-night", "solo-dining"],
    price_tier: "$$$",
    notes: "No-reservations. Two-hour wait normal.",
  },
  {
    slug: "raouls",
    name: "Raoul's",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["raouls", "raoul's au poivre burger"],
    cuisines: ["french"],
    occasions: ["date-night", "late-night"],
    price_tier: "$$$",
    notes: "The au poivre burger. Bar-only.",
  },
  {
    slug: "i-sodi",
    name: "I Sodi",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["i sodi", "i sodi nyc", "lasagna i sodi"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Tuscan, intimate, hard-to-book. Quiet excellence.",
  },
  {
    slug: "rezdora",
    name: "Rezdôra",
    neighborhood: "Flatiron",
    borough: "manhattan",
    search_terms: ["rezdora", "rezdora nyc", "emilia romagna pasta"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
  },
  {
    slug: "lilia",
    name: "Lilia",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["lilia williamsburg", "lilia missy robbins"],
    cuisines: ["italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
  },
  {
    slug: "misi",
    name: "Misi",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["misi nyc", "misi pasta", "missy robbins misi"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
  },

  // ===========================================================
  // PIZZA — late night + under $25 + solo
  // ===========================================================
  {
    slug: "lucali",
    name: "Lucali",
    neighborhood: "Carroll Gardens",
    borough: "brooklyn",
    search_terms: ["lucali", "lucali pizza brooklyn"],
    cuisines: ["pizza", "italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "BYOB pizza. Four-hour wait is the experience.",
  },
  {
    slug: "joes-pizza",
    name: "Joe's Pizza",
    neighborhood: "Greenwich Village",
    borough: "manhattan",
    search_terms: ["joes pizza nyc", "joe's pizza carmine"],
    cuisines: ["pizza"],
    occasions: ["late-night", "under-25", "solo-dining"],
    price_tier: "$",
  },
  {
    slug: "scarrs-pizza",
    name: "Scarr's Pizza",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["scarrs pizza", "scarrs nyc", "scarr's lower east side"],
    cuisines: ["pizza"],
    occasions: ["late-night", "under-25", "solo-dining"],
    price_tier: "$",
  },
  {
    slug: "lartusi",
    name: "L'Artusi",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["lartusi", "l'artusi west village"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
  },
  {
    slug: "rubirosa",
    name: "Rubirosa",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["rubirosa", "rubirosa tie dye pizza"],
    cuisines: ["pizza", "italian"],
    occasions: ["group-dinner", "date-night"],
    price_tier: "$$",
    notes: "The tie-dye pizza is the entire Instagram caption.",
  },
  {
    slug: "prince-st-pizza",
    name: "Prince Street Pizza",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["prince street pizza", "prince st pizza spicy spring"],
    cuisines: ["pizza"],
    occasions: ["under-25", "solo-dining", "late-night"],
    price_tier: "$",
  },

  // ===========================================================
  // KOREAN
  // ===========================================================
  {
    slug: "cote",
    name: "COTE",
    neighborhood: "Flatiron",
    borough: "manhattan",
    search_terms: ["cote korean steakhouse", "cote nyc"],
    cuisines: ["korean"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
    notes: "Korean steakhouse. Has Miami and Vegas locations now.",
  },
  {
    slug: "atomix",
    name: "Atomix",
    neighborhood: "NoMad",
    borough: "manhattan",
    search_terms: ["atomix", "atomix korean", "atomix nyc"],
    cuisines: ["korean"],
    occasions: ["date-night"],
    price_tier: "$$$$",
    notes: "Korean tasting menu. 2 Michelin stars.",
  },
  {
    slug: "kochi",
    name: "Kochi",
    neighborhood: "Hell's Kitchen",
    borough: "manhattan",
    search_terms: ["kochi nyc", "kochi korean tasting menu"],
    cuisines: ["korean"],
    occasions: ["date-night"],
    price_tier: "$$$",
  },
  {
    slug: "her-name-is-han",
    name: "Her Name Is Han",
    neighborhood: "Koreatown",
    borough: "manhattan",
    search_terms: ["her name is han", "her name is han ktown"],
    cuisines: ["korean"],
    occasions: ["group-dinner"],
    price_tier: "$$",
  },
  {
    slug: "sik-gaek",
    name: "Sik Gaek",
    neighborhood: "Flushing",
    borough: "queens",
    search_terms: ["sik gaek flushing", "sik gaek queens", "live octopus"],
    cuisines: ["korean"],
    occasions: ["group-dinner", "late-night"],
    price_tier: "$$",
    notes: "Live octopus, Soju nights. Locals love it.",
  },

  // ===========================================================
  // JAPANESE
  // ===========================================================
  {
    slug: "sushi-nakazawa",
    name: "Sushi Nakazawa",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["sushi nakazawa", "nakazawa omakase"],
    cuisines: ["japanese"],
    occasions: ["date-night", "solo-dining"],
    price_tier: "$$$$",
  },
  {
    slug: "sushi-noz",
    name: "Sushi Noz",
    neighborhood: "Upper East Side",
    borough: "manhattan",
    search_terms: ["sushi noz", "sushi noz upper east side"],
    cuisines: ["japanese"],
    occasions: ["date-night", "solo-dining"],
    price_tier: "$$$$",
  },
  {
    slug: "tomoe-sushi",
    name: "Tomoe Sushi",
    neighborhood: "Greenwich Village",
    borough: "manhattan",
    search_terms: ["tomoe sushi", "tomoe nyc"],
    cuisines: ["japanese"],
    occasions: ["solo-dining", "date-night"],
    price_tier: "$$",
    notes: "Cash only. Locals know.",
  },
  {
    slug: "ootoya-chelsea",
    name: "Ootoya",
    neighborhood: "Chelsea",
    borough: "manhattan",
    search_terms: ["ootoya nyc", "ootoya chelsea"],
    cuisines: ["japanese"],
    occasions: ["solo-dining", "under-25"],
    price_tier: "$$",
  },
  {
    slug: "ippudo",
    name: "Ippudo",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["ippudo nyc", "ippudo ramen"],
    cuisines: ["japanese"],
    occasions: ["solo-dining", "late-night"],
    price_tier: "$$",
  },
  {
    slug: "ichiran",
    name: "Ichiran",
    neighborhood: "Bushwick",
    borough: "brooklyn",
    search_terms: ["ichiran ramen", "ichiran brooklyn"],
    cuisines: ["japanese"],
    occasions: ["solo-dining", "late-night"],
    price_tier: "$$",
    notes: "The solo booth ramen experience.",
  },

  // ===========================================================
  // CHINESE
  // ===========================================================
  {
    slug: "wus-wonton-king",
    name: "Wu's Wonton King",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["wus wonton king", "wonton king nyc"],
    cuisines: ["chinese"],
    occasions: ["group-dinner", "under-25"],
    price_tier: "$$",
    notes: "BYOB Cantonese. Locals know.",
  },
  {
    slug: "cafe-china",
    name: "Cafe China",
    neighborhood: "Midtown",
    borough: "manhattan",
    search_terms: ["cafe china nyc", "cafe china sichuan"],
    cuisines: ["chinese"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "Sichuan. Quietly a real one.",
  },
  {
    slug: "joes-shanghai",
    name: "Joe's Shanghai",
    neighborhood: "Flushing",
    borough: "queens",
    search_terms: ["joes shanghai", "soup dumplings nyc"],
    cuisines: ["chinese"],
    occasions: ["group-dinner", "under-25"],
    price_tier: "$$",
  },
  {
    slug: "bonnies",
    name: "Bonnie's",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["bonnies williamsburg", "bonnies cantonese"],
    cuisines: ["chinese"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Cantonese-American. TikTok favorite.",
  },
  {
    slug: "ho-foods",
    name: "Ho Foods",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["ho foods nyc", "beef noodle soup ho foods"],
    cuisines: ["chinese"],
    occasions: ["solo-dining", "under-25"],
    price_tier: "$$",
    notes: "Taiwanese beef noodle. Quiet excellence.",
  },
  {
    slug: "nan-xiang",
    name: "Nan Xiang Xiao Long Bao",
    neighborhood: "Flushing",
    borough: "queens",
    search_terms: ["nan xiang xiao long bao", "nan xiang flushing"],
    cuisines: ["chinese"],
    occasions: ["group-dinner", "under-25"],
    price_tier: "$",
  },

  // ===========================================================
  // INDIAN
  // ===========================================================
  {
    slug: "ambassadors-clubhouse",
    name: "Ambassador's Clubhouse",
    neighborhood: "NoMad",
    borough: "manhattan",
    search_terms: ["ambassadors clubhouse", "punjabi nyc"],
    cuisines: ["indian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Currently the most impossible reservation.",
  },
  {
    slug: "semma",
    name: "Semma",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["semma nyc", "semma south indian"],
    cuisines: ["indian"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Michelin-starred South Indian. Earned it.",
  },
  {
    slug: "dhamaka",
    name: "Dhamaka",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["dhamaka nyc", "dhamaka lower east side"],
    cuisines: ["indian"],
    occasions: ["group-dinner"],
    price_tier: "$$$",
  },
  {
    slug: "adda",
    name: "Adda",
    neighborhood: "Long Island City",
    borough: "queens",
    search_terms: ["adda nyc", "adda lic", "adda indian"],
    cuisines: ["indian"],
    occasions: ["group-dinner"],
    price_tier: "$$",
    notes: "Unfiltered Indian. Locals love.",
  },
  {
    slug: "junoon",
    name: "Junoon",
    neighborhood: "Flatiron",
    borough: "manhattan",
    search_terms: ["junoon nyc", "junoon flatiron"],
    cuisines: ["indian"],
    occasions: ["date-night"],
    price_tier: "$$$$",
  },

  // ===========================================================
  // MEXICAN
  // ===========================================================
  {
    slug: "cosme",
    name: "Cosme",
    neighborhood: "Flatiron",
    borough: "manhattan",
    search_terms: ["cosme nyc", "cosme husk meringue"],
    cuisines: ["mexican"],
    occasions: ["date-night"],
    price_tier: "$$$$",
    notes: "Husk meringue is the Instagram caption.",
  },
  {
    slug: "casa-enrique",
    name: "Casa Enrique",
    neighborhood: "Long Island City",
    borough: "queens",
    search_terms: ["casa enrique", "casa enrique lic"],
    cuisines: ["mexican"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "Michelin Mexican in LIC. Local secret.",
  },
  {
    slug: "tacombi",
    name: "Tacombi",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["tacombi nyc", "tacombi nolita"],
    cuisines: ["mexican"],
    occasions: ["under-25", "brunch"],
    price_tier: "$$",
  },
  {
    slug: "los-tacos-no1",
    name: "Los Tacos No. 1",
    neighborhood: "Chelsea Market",
    borough: "manhattan",
    search_terms: ["los tacos no 1", "los tacos chelsea market"],
    cuisines: ["mexican"],
    occasions: ["under-25", "solo-dining", "late-night"],
    price_tier: "$",
  },
  {
    slug: "oxomoco",
    name: "Oxomoco",
    neighborhood: "Greenpoint",
    borough: "brooklyn",
    search_terms: ["oxomoco brooklyn", "oxomoco greenpoint"],
    cuisines: ["mexican"],
    occasions: ["date-night", "brunch"],
    price_tier: "$$$",
  },

  // ===========================================================
  // FRENCH
  // ===========================================================
  {
    slug: "le-bernardin",
    name: "Le Bernardin",
    neighborhood: "Midtown",
    borough: "manhattan",
    search_terms: ["le bernardin", "ripert le bernardin"],
    cuisines: ["french"],
    occasions: ["date-night"],
    price_tier: "$$$$",
  },
  {
    slug: "le-coucou",
    name: "Le Coucou",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["le coucou nyc", "le coucou soho"],
    cuisines: ["french"],
    occasions: ["date-night"],
    price_tier: "$$$$",
  },
  {
    slug: "frenchette",
    name: "Frenchette",
    neighborhood: "TriBeCa",
    borough: "manhattan",
    search_terms: ["frenchette tribeca", "frenchette nyc"],
    cuisines: ["french"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
  },
  {
    slug: "buvette",
    name: "Buvette",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["buvette nyc", "buvette west village brunch"],
    cuisines: ["french"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
  },
  {
    slug: "balthazar",
    name: "Balthazar",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["balthazar nyc", "balthazar brunch soho"],
    cuisines: ["french"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
  },

  // ===========================================================
  // THAI
  // ===========================================================
  {
    slug: "fish-cheeks",
    name: "Fish Cheeks",
    neighborhood: "NoHo",
    borough: "manhattan",
    search_terms: ["fish cheeks nyc", "fish cheeks thai"],
    cuisines: ["thai"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
  },
  {
    slug: "uncle-boons-sister",
    name: "Thai Diner",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["thai diner nyc", "thai diner nolita"],
    cuisines: ["thai"],
    occasions: ["brunch", "group-dinner"],
    price_tier: "$$",
  },
  {
    slug: "sripraphai",
    name: "SriPraPhai",
    neighborhood: "Woodside",
    borough: "queens",
    search_terms: ["sripraphai", "sripraphai woodside thai"],
    cuisines: ["thai"],
    occasions: ["group-dinner", "under-25"],
    price_tier: "$$",
    notes: "The locals' Thai. Real heat.",
  },
  {
    slug: "soothr",
    name: "Soothr",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["soothr nyc", "soothr east village"],
    cuisines: ["thai"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
  },

  // ===========================================================
  // MEDITERRANEAN
  // ===========================================================
  {
    slug: "cafe-mogador",
    name: "Cafe Mogador",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["cafe mogador", "mogador brunch"],
    cuisines: ["mediterranean"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$",
    notes: "Moroccan brunch institution.",
  },
  {
    slug: "miss-ada",
    name: "Miss Ada",
    neighborhood: "Fort Greene",
    borough: "brooklyn",
    search_terms: ["miss ada brooklyn", "miss ada fort greene"],
    cuisines: ["mediterranean"],
    occasions: ["date-night", "brunch"],
    price_tier: "$$$",
  },
  {
    slug: "eyval",
    name: "Eyval",
    neighborhood: "Bushwick",
    borough: "brooklyn",
    search_terms: ["eyval bushwick", "eyval persian"],
    cuisines: ["mediterranean"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Persian. Earned every star without TikTok.",
  },
  {
    slug: "shukette",
    name: "Shukette",
    neighborhood: "Chelsea",
    borough: "manhattan",
    search_terms: ["shukette nyc", "shukette chelsea"],
    cuisines: ["mediterranean"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
  },
  {
    slug: "12-chairs",
    name: "12 Chairs Café",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["12 chairs cafe soho", "12 chairs israeli"],
    cuisines: ["mediterranean"],
    occasions: ["brunch", "solo-dining"],
    price_tier: "$$",
  },

  // ===========================================================
  // AMERICAN — burgers, brunch, classics
  // ===========================================================
  {
    slug: "polo-bar",
    name: "The Polo Bar",
    neighborhood: "Midtown East",
    borough: "manhattan",
    search_terms: ["polo bar", "ralph lauren polo bar"],
    cuisines: ["american"],
    occasions: ["date-night"],
    price_tier: "$$$$",
    notes: "Six-month wait for non-celebs.",
  },
  {
    slug: "eighty-six",
    name: "The Eighty-Six",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["the eighty-six", "the eighty six nyc"],
    cuisines: ["american"],
    occasions: ["date-night", "late-night"],
    price_tier: "$$$",
    notes: "Members-only-feeling.",
  },
  {
    slug: "tatiana",
    name: "Tatiana",
    neighborhood: "Lincoln Square",
    borough: "manhattan",
    search_terms: ["tatiana kwame", "tatiana lincoln center"],
    cuisines: ["american"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
    notes: "Kwame Onwuachi.",
  },
  {
    slug: "mels",
    name: "Mel's",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["mels nyc", "mel's soho", "mels burger"],
    cuisines: ["american"],
    occasions: ["brunch", "late-night"],
    price_tier: "$$$",
    notes: "The cheeseburger is the Instagram caption.",
  },
  {
    slug: "jacks-wife-freda",
    name: "Jack's Wife Freda",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["jacks wife freda", "green shakshuka"],
    cuisines: ["mediterranean", "american"],
    occasions: ["brunch"],
    price_tier: "$$",
    notes: "Green shakshuka.",
  },
  {
    slug: "russ-and-daughters",
    name: "Russ & Daughters Cafe",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["russ and daughters", "russ daughters cafe"],
    cuisines: ["american"],
    occasions: ["brunch"],
    price_tier: "$$",
  },
  {
    slug: "katzs",
    name: "Katz's Delicatessen",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["katzs deli", "katz's pastrami"],
    cuisines: ["american"],
    occasions: ["solo-dining", "late-night", "under-25"],
    price_tier: "$$",
  },
  {
    slug: "veselka",
    name: "Veselka",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["veselka", "veselka pierogi"],
    cuisines: ["american"],
    occasions: ["late-night", "brunch", "under-25"],
    price_tier: "$$",
    notes: "Ukrainian classic. Real institution.",
  },
  {
    slug: "diner",
    name: "Diner",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["diner williamsburg", "diner brooklyn"],
    cuisines: ["american"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
  },
  {
    slug: "four-horsemen",
    name: "Four Horsemen",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["four horsemen", "four horsemen wine bar"],
    cuisines: ["american"],
    occasions: ["date-night", "solo-dining"],
    price_tier: "$$$",
    notes: "Natural wine + small plates. James Murphy's spot.",
  },
  {
    slug: "cervos",
    name: "Cervo's",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["cervos nyc", "cervo's"],
    cuisines: ["mediterranean"],
    occasions: ["date-night", "solo-dining"],
    price_tier: "$$$",
  },
  {
    slug: "llama-san",
    name: "Llama San",
    neighborhood: "Greenwich Village",
    borough: "manhattan",
    search_terms: ["llama san nyc", "llama san peruvian"],
    cuisines: ["japanese"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Peruvian-Japanese (Nikkei).",
  },

  // ===========================================================
  // BRUNCH heavy-hitters
  // ===========================================================
  {
    slug: "clinton-st-baking",
    name: "Clinton St. Baking Company",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["clinton street baking", "clinton st pancakes"],
    cuisines: ["american"],
    occasions: ["brunch"],
    price_tier: "$$",
    notes: "The blueberry pancake hype machine.",
  },
  {
    slug: "sadelles",
    name: "Sadelle's",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["sadelles soho", "sadelles brunch"],
    cuisines: ["american"],
    occasions: ["brunch"],
    price_tier: "$$$",
  },
  {
    slug: "egg-shop",
    name: "Egg Shop",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["egg shop nolita", "egg shop nyc"],
    cuisines: ["american"],
    occasions: ["brunch"],
    price_tier: "$$",
  },

  // ===========================================================
  // LATE NIGHT extras
  // ===========================================================
  {
    slug: "wo-hop",
    name: "Wo Hop",
    neighborhood: "Chinatown",
    borough: "manhattan",
    search_terms: ["wo hop chinatown", "wo hop late night"],
    cuisines: ["chinese"],
    occasions: ["late-night", "under-25"],
    price_tier: "$",
    notes: "Open till 4am. The drunk meal.",
  },
  {
    slug: "frenchman",
    name: "The Frenchman's",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["the frenchmans nyc", "frenchmans east village"],
    cuisines: ["french"],
    occasions: ["late-night", "date-night"],
    price_tier: "$$$",
  },

  // ===========================================================
  // UNDER $25 extras
  // ===========================================================
  {
    slug: "xian-famous",
    name: "Xi'an Famous Foods",
    neighborhood: "Multiple",
    borough: "manhattan",
    search_terms: ["xian famous foods", "xian biang biang noodles"],
    cuisines: ["chinese"],
    occasions: ["under-25", "solo-dining"],
    price_tier: "$",
  },
  {
    slug: "punjabi-deli",
    name: "Punjabi Grocery & Deli",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["punjabi grocery deli", "punjabi deli east village"],
    cuisines: ["indian"],
    occasions: ["under-25", "late-night", "solo-dining"],
    price_tier: "$",
    notes: "Cheapest dal in Manhattan. Open 24/7.",
  },
  {
    slug: "vanessas-dumplings",
    name: "Vanessa's Dumpling House",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["vanessas dumplings", "vanessa dumpling house"],
    cuisines: ["chinese"],
    occasions: ["under-25", "solo-dining"],
    price_tier: "$",
  },
  // ===========================================================
  // PHASE 2 — Expansion: fancy/Instagrammable, tourist traps, locals' canon,
  // cuisine gaps, newer openings, Korean BBQ fill. 80 restaurants → 157 total.
  // ===========================================================
  {
    slug: "sant-ambroeus-ues",
    name: "Sant Ambroeus",
    neighborhood: "Upper East Side",
    borough: "manhattan",
    search_terms: ["sant ambroeus", "sant ambroeus madison"],
    cuisines: ["italian"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
    notes: "Old money in linen. The cappuccino does the work.",
  },
  {
    slug: "sant-ambroeus-wv",
    name: "Sant Ambroeus West Village",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["sant ambroeus west village", "sant ambroeus perry"],
    cuisines: ["italian"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
    notes: "Perry Street's pretty-people lunch.",
  },
  {
    slug: "pastis",
    name: "Pastis",
    neighborhood: "Meatpacking District",
    borough: "manhattan",
    search_terms: ["pastis nyc", "pastis brunch"],
    cuisines: ["french"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
    notes: "Resurrected for the photo, not the steak frites.",
  },
  {
    slug: "cipriani-downtown",
    name: "Cipriani Downtown",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["cipriani downtown soho", "cipriani west broadway"],
    cuisines: ["italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
    notes: "Bellinis and finance bros. The veal does what it can.",
  },
  {
    slug: "bar-pitti",
    name: "Bar Pitti",
    neighborhood: "Greenwich Village",
    borough: "manhattan",
    search_terms: ["bar pitti nyc", "bar pitti sixth avenue"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "No reservations, all celebrities. Cash only, vibes plenty.",
  },
  {
    slug: "the-corner-store",
    name: "The Corner Store",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["the corner store soho", "corner store nyc"],
    cuisines: ["american"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
    notes: "Buzzy New American in a corner. Food chases the room.",
  },
  {
    slug: "le-veau-dor",
    name: "Le Veau d'Or",
    neighborhood: "Upper East Side",
    borough: "manhattan",
    search_terms: ["le veau dor", "veau dor uptown"],
    cuisines: ["french"],
    occasions: ["date-night"],
    price_tier: "$$$$",
    notes: "Reopened French institution. Old-money revival energy.",
  },
  {
    slug: "caviar-russe",
    name: "Caviar Russe",
    neighborhood: "Midtown East",
    borough: "manhattan",
    search_terms: ["caviar russe", "caviar russe madison"],
    cuisines: ["american"],
    occasions: ["date-night"],
    price_tier: "$$$$",
    notes: "Tiny upstairs caviar room. Mostly tourists with deep wallets.",
  },
  {
    slug: "portrait-bar",
    name: "The Portrait Bar",
    neighborhood: "NoMad",
    borough: "manhattan",
    search_terms: ["portrait bar fifth avenue hotel", "portrait bar nomad"],
    cuisines: ["american"],
    occasions: ["date-night", "late-night"],
    price_tier: "$$$$",
    notes: "Inside The Fifth Avenue Hotel. Cocktail spectacle.",
  },
  {
    slug: "bemelmans-bar",
    name: "Bemelmans Bar",
    neighborhood: "Upper East Side",
    borough: "manhattan",
    search_terms: ["bemelmans bar carlyle", "bemelmans cocktails"],
    cuisines: ["american"],
    occasions: ["date-night", "late-night"],
    price_tier: "$$$",
    notes: "Murals worth the cover charge. Drinks adequate at best.",
  },
  {
    slug: "tao-downtown",
    name: "Tao Downtown",
    neighborhood: "Chelsea",
    borough: "manhattan",
    search_terms: ["tao downtown", "tao chelsea"],
    cuisines: ["japanese"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Big Buddha, bigger checks. Pan-Asian for bachelorettes.",
  },
  {
    slug: "buddakan",
    name: "Buddakan",
    neighborhood: "Chelsea",
    borough: "manhattan",
    search_terms: ["buddakan nyc", "buddakan chelsea"],
    cuisines: ["japanese"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Sex and the City filming location, still charges 2004 hype prices.",
  },
  {
    slug: "catch-steak",
    name: "Catch Steak",
    neighborhood: "Meatpacking District",
    borough: "manhattan",
    search_terms: ["catch steak nyc", "catch steak meatpacking"],
    cuisines: ["american"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
    notes: "Influencer beef. Sundaes set on fire.",
  },
  {
    slug: "sushi-by-bou",
    name: "Sushi by Bou",
    neighborhood: "Midtown",
    borough: "manhattan",
    search_terms: ["sushi by bou", "sushi by bou speakeasy"],
    cuisines: ["japanese"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "30-minute omakase speakeasy chain. TikTok's omakase entry drug.",
  },
  {
    slug: "cha-cha-matcha",
    name: "Cha Cha Matcha",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["cha cha matcha", "cha cha matcha nolita"],
    cuisines: ["american"],
    occasions: ["brunch", "under-25"],
    price_tier: "$",
    notes: "Pink walls, lavender lattes. Made for the post.",
  },
  {
    slug: "magic-hour-rooftop",
    name: "Magic Hour Rooftop",
    neighborhood: "Midtown",
    borough: "manhattan",
    search_terms: ["magic hour rooftop moxy", "magic hour times square"],
    cuisines: ["american"],
    occasions: ["date-night", "late-night"],
    price_tier: "$$$",
    notes: "Mini-putt and pink roses on a Times Square rooftop. Food irrelevant.",
  },
  {
    slug: "la-mercerie",
    name: "La Mercerie",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["la mercerie soho", "la mercerie nyc"],
    cuisines: ["french"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
    notes: "Inside Roman & Williams Guild. Tablescape first, food second.",
  },
  {
    slug: "loring-place",
    name: "Loring Place",
    neighborhood: "Greenwich Village",
    borough: "manhattan",
    search_terms: ["loring place nyc", "loring place dan kluger"],
    cuisines: ["american"],
    occasions: ["date-night", "brunch"],
    price_tier: "$$$",
    notes: "Vegetable-forward New American. Wood-fired and well-lit.",
  },
  {
    slug: "bar-primi",
    name: "Bar Primi",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["bar primi nyc", "bar primi bowery"],
    cuisines: ["italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "Andrew Carmellini pasta in a designed-to-be-loud room.",
  },
  {
    slug: "olio-e-piu",
    name: "Olio e Più",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["olio e piu", "olio e piu west village"],
    cuisines: ["italian"],
    occasions: ["date-night", "brunch"],
    price_tier: "$$",
    notes: "Greenery, fairy lights, $26 pasta. Influencer Italian.",
  },
  {
    slug: "maison-close",
    name: "Maison Close",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["maison close nyc", "maison close soho"],
    cuisines: ["french"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
    notes: "Boudoir-themed brunch spot. The decor outperforms the eggs.",
  },
  {
    slug: "felice",
    name: "Felice",
    neighborhood: "Upper East Side",
    borough: "manhattan",
    search_terms: ["felice nyc", "felice midtown"],
    cuisines: ["italian"],
    occasions: ["date-night", "brunch"],
    price_tier: "$$",
    notes: "Italian wine bar chain across Manhattan. Pretty rooms, fine food.",
  },
  {
    slug: "maman",
    name: "Maman",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["maman cafe", "maman nyc"],
    cuisines: ["french"],
    occasions: ["brunch", "solo-dining"],
    price_tier: "$$",
    notes: "Cottagecore croissants. Better at branding than baking.",
  },
  {
    slug: "magnolia-bakery",
    name: "Magnolia Bakery",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["magnolia bakery", "magnolia banana pudding"],
    cuisines: ["american"],
    occasions: ["brunch"],
    price_tier: "$",
    notes: "Banana pudding, line out the door. Cupcakes haven't been good since 2008.",
  },
  {
    slug: "carmines",
    name: "Carmine's",
    neighborhood: "Theater District",
    borough: "manhattan",
    search_terms: ["carmines times square", "carmines family style"],
    cuisines: ["italian"],
    occasions: ["group-dinner"],
    price_tier: "$$",
    notes: "Family-style platters for confused tourists.",
  },
  {
    slug: "lombardis-pizza",
    name: "Lombardi's Pizza",
    neighborhood: "Little Italy",
    borough: "manhattan",
    search_terms: ["lombardis pizza", "lombardis little italy"],
    cuisines: ["pizza"],
    occasions: ["under-25", "solo-dining"],
    price_tier: "$",
    notes: "America's first pizzeria. The pie now coasts on the plaque.",
  },
  {
    slug: "ellens-stardust",
    name: "Ellen's Stardust Diner",
    neighborhood: "Theater District",
    borough: "manhattan",
    search_terms: ["ellens stardust diner", "ellens singing waiters"],
    cuisines: ["american"],
    occasions: ["brunch", "group-dinner"],
    price_tier: "$$",
    notes: "Singing waiters, frozen-then-microwaved fries.",
  },
  {
    slug: "serendipity-3",
    name: "Serendipity 3",
    neighborhood: "Upper East Side",
    borough: "manhattan",
    search_terms: ["serendipity 3", "serendipity frozen hot chocolate"],
    cuisines: ["american"],
    occasions: ["brunch"],
    price_tier: "$$",
    notes: "$25 frozen hot chocolate and a 90-minute wait.",
  },
  {
    slug: "juniors",
    name: "Junior's",
    neighborhood: "Theater District",
    borough: "manhattan",
    search_terms: ["juniors cheesecake", "juniors times square"],
    cuisines: ["american"],
    occasions: ["brunch", "under-25"],
    price_tier: "$$",
    notes: "Cheesecake worth the calories. The rest of the menu, not so much.",
  },
  {
    slug: "bubba-gump",
    name: "Bubba Gump",
    neighborhood: "Times Square",
    borough: "manhattan",
    search_terms: ["bubba gump times square", "bubba gump shrimp"],
    cuisines: ["american"],
    occasions: ["group-dinner"],
    price_tier: "$$",
    notes: "Movie tie-in chain. Shrimp by way of corporate America.",
  },
  {
    slug: "olive-garden-times-square",
    name: "Olive Garden Times Square",
    neighborhood: "Times Square",
    borough: "manhattan",
    search_terms: ["olive garden times square"],
    cuisines: ["italian"],
    occasions: ["group-dinner"],
    price_tier: "$$",
    notes: "Unlimited breadsticks. Times Square's biggest red flag.",
  },
  {
    slug: "lindustrie-pizzeria",
    name: "L'Industrie Pizzeria",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["lindustrie pizzeria", "industrie burrata slice"],
    cuisines: ["pizza"],
    occasions: ["under-25", "solo-dining"],
    price_tier: "$",
    notes: "Burrata slice that broke TikTok. Worth a line, but not three hours.",
  },
  {
    slug: "robertas",
    name: "Roberta's",
    neighborhood: "Bushwick",
    borough: "brooklyn",
    search_terms: ["robertas pizza bushwick", "robertas bee sting"],
    cuisines: ["pizza"],
    occasions: ["group-dinner", "brunch"],
    price_tier: "$$",
    notes: "Bushwick pizza institution. Bee Sting still slaps.",
  },
  {
    slug: "levain-bakery",
    name: "Levain Bakery",
    neighborhood: "Upper West Side",
    borough: "manhattan",
    search_terms: ["levain bakery cookies", "levain ues"],
    cuisines: ["american"],
    occasions: ["under-25"],
    price_tier: "$",
    notes: "Cookie the size of a softball. $5.50 of dopamine.",
  },
  {
    slug: "westville",
    name: "Westville",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["westville west village", "westville market vegetables"],
    cuisines: ["american"],
    occasions: ["brunch", "solo-dining"],
    price_tier: "$$",
    notes: "Sixteen vegetable sides. The chicken does its best.",
  },
  {
    slug: "emilios-ballato",
    name: "Emilio's Ballato",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["emilios ballato", "ballato east houston"],
    cuisines: ["italian"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Old-school red sauce, Obama once ate here.",
  },
  {
    slug: "lucien",
    name: "Lucien",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["lucien nyc", "lucien first avenue"],
    cuisines: ["french"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Late-night Frenchman favorite. Steak frites for the model crowd.",
  },
  {
    slug: "four-charles-prime-rib",
    name: "4 Charles Prime Rib",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["4 charles prime rib", "four charles steakhouse"],
    cuisines: ["american"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
    notes: "Eight-month wait for a steakhouse with sixteen seats.",
  },
  {
    slug: "spicy-village",
    name: "Spicy Village",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["spicy village henan", "spicy village forsyth"],
    cuisines: ["chinese"],
    occasions: ["under-25"],
    price_tier: "$",
    notes: "Henan hand-pulled noodles. Twelve bucks of joy.",
  },
  {
    slug: "great-ny-noodletown",
    name: "Great NY Noodletown",
    neighborhood: "Chinatown",
    borough: "manhattan",
    search_terms: ["great ny noodletown", "ny noodletown chinatown"],
    cuisines: ["chinese"],
    occasions: ["late-night", "under-25"],
    price_tier: "$",
    notes: "Salt-baked seafood and roast meats. Open till 4am.",
  },
  {
    slug: "456-shanghai",
    name: "456 Shanghai Cuisine",
    neighborhood: "Chinatown",
    borough: "manhattan",
    search_terms: ["456 shanghai cuisine", "456 mott shanghai"],
    cuisines: ["chinese"],
    occasions: ["group-dinner", "under-25"],
    price_tier: "$$",
    notes: "Soup dumplings and pork shoulder. Locals' overflow from Joe's Shanghai.",
  },
  {
    slug: "hwa-yuan",
    name: "Hwa Yuan",
    neighborhood: "Chinatown",
    borough: "manhattan",
    search_terms: ["hwa yuan szechuan", "hwa yuan east broadway"],
    cuisines: ["chinese"],
    occasions: ["group-dinner"],
    price_tier: "$$",
    notes: "Three floors of Szechuan ambition.",
  },
  {
    slug: "birds-of-a-feather",
    name: "Birds of a Feather",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["birds of a feather williamsburg", "birds feather sichuan"],
    cuisines: ["chinese"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "Sichuan, but make it date night.",
  },
  {
    slug: "cafe-katja",
    name: "Café Katja",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["cafe katja", "katja austrian"],
    cuisines: ["american"],
    occasions: ["solo-dining", "date-night"],
    price_tier: "$$",
    notes: "Schnitzel and Austrian beer at a tiny LES bar.",
  },
  {
    slug: "prune",
    name: "Prune",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["prune nyc", "prune east 1st"],
    cuisines: ["american"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$$",
    notes: "Gabrielle Hamilton's tiny East Village staple. Mostly brunch fights.",
  },
  {
    slug: "atla",
    name: "Atla",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["atla nyc", "atla cosme"],
    cuisines: ["mexican"],
    occasions: ["brunch", "date-night"],
    price_tier: "$$",
    notes: "Daytime Cosme. Better priced, equally precise.",
  },
  {
    slug: "estela",
    name: "Estela",
    neighborhood: "NoLIta",
    borough: "manhattan",
    search_terms: ["estela nyc", "estela houston street"],
    cuisines: ["mediterranean"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Mussel toast and burrata. A reservation that means something.",
  },
  {
    slug: "llama-inn",
    name: "Llama Inn",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["llama inn williamsburg", "llama inn peruvian"],
    cuisines: ["mediterranean"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "Peruvian small plates. Brooklyn's quietest hit.",
  },
  {
    slug: "hometown-bbq",
    name: "Hometown Bar-B-Que",
    neighborhood: "Red Hook",
    borough: "brooklyn",
    search_terms: ["hometown bbq red hook", "hometown brisket"],
    cuisines: ["american"],
    occasions: ["group-dinner", "under-25"],
    price_tier: "$$",
    notes: "Brisket worth the Red Hook trek.",
  },
  {
    slug: "mighty-quinns",
    name: "Mighty Quinn's BBQ",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["mighty quinns bbq", "mighty quinns brisket"],
    cuisines: ["american"],
    occasions: ["under-25", "solo-dining"],
    price_tier: "$",
    notes: "Counter-service BBQ that doesn't insult Texas.",
  },
  {
    slug: "khe-yo",
    name: "Khe-Yo",
    neighborhood: "TriBeCa",
    borough: "manhattan",
    search_terms: ["khe-yo tribeca", "khe yo laotian"],
    cuisines: ["thai"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "Laotian sticky rice and jeow. Underrated for years.",
  },
  {
    slug: "tompkins-square-bagels",
    name: "Tompkins Square Bagels",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["tompkins square bagels", "tsb east village"],
    cuisines: ["american"],
    occasions: ["brunch", "under-25"],
    price_tier: "$",
    notes: "Flavored cream cheese pile-ons. Bagel itself is fine.",
  },
  {
    slug: "ess-a-bagel",
    name: "Ess-a-Bagel",
    neighborhood: "Midtown",
    borough: "manhattan",
    search_terms: ["ess a bagel", "ess a bagel midtown"],
    cuisines: ["american"],
    occasions: ["brunch", "under-25"],
    price_tier: "$",
    notes: "Bagels the size of a frisbee. Quintessential NYC line.",
  },
  {
    slug: "court-street-grocers",
    name: "Court Street Grocers",
    neighborhood: "Carroll Gardens",
    borough: "brooklyn",
    search_terms: ["court street grocers", "csg sandwich"],
    cuisines: ["american"],
    occasions: ["under-25", "solo-dining"],
    price_tier: "$",
    notes: "Italian sub done right in a deli that looks the part.",
  },
  {
    slug: "defontes",
    name: "Defontes",
    neighborhood: "Brooklyn Heights",
    borough: "brooklyn",
    search_terms: ["defontes sandwich", "defontes red hook"],
    cuisines: ["american"],
    occasions: ["under-25"],
    price_tier: "$",
    notes: "Red Hook sub institution. Eat one while you're young.",
  },
  {
    slug: "banh-mi-saigon",
    name: "Banh Mi Saigon",
    neighborhood: "Chinatown",
    borough: "manhattan",
    search_terms: ["banh mi saigon", "banh mi mott street"],
    cuisines: ["thai"],
    occasions: ["under-25"],
    price_tier: "$",
    notes: "Cheap, sharp banh mi a block off Canal.",
  },
  {
    slug: "hanoi-house",
    name: "Hanoi House",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["hanoi house nyc", "hanoi house pho"],
    cuisines: ["thai"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "Hanoi-style pho with deep beef broth and date-night lighting.",
  },
  {
    slug: "maharlika",
    name: "Maharlika",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["maharlika filipino", "maharlika first avenue"],
    cuisines: ["thai"],
    occasions: ["brunch", "group-dinner"],
    price_tier: "$$",
    notes: "Filipino brunch with ube pancakes. NYC's most underrated cuisine.",
  },
  {
    slug: "jeepney",
    name: "Jeepney",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["jeepney filipino", "jeepney first avenue"],
    cuisines: ["thai"],
    occasions: ["group-dinner"],
    price_tier: "$$",
    notes: "Filipino group dinners. Kamayan feasts and karaoke energy.",
  },
  {
    slug: "superiority-burger",
    name: "Superiority Burger",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["superiority burger", "superiority burger nyc"],
    cuisines: ["american"],
    occasions: ["under-25", "solo-dining"],
    price_tier: "$",
    notes: "Vegan burger that converts skeptics.",
  },
  {
    slug: "dirt-candy",
    name: "Dirt Candy",
    neighborhood: "Lower East Side",
    borough: "manhattan",
    search_terms: ["dirt candy nyc", "dirt candy amanda cohen"],
    cuisines: ["american"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Vegetable tasting menu. Treats produce like protein.",
  },
  {
    slug: "lighthouse",
    name: "Lighthouse",
    neighborhood: "Williamsburg",
    borough: "brooklyn",
    search_terms: ["lighthouse williamsburg", "lighthouse brunch nyc"],
    cuisines: ["mediterranean"],
    occasions: ["date-night", "brunch"],
    price_tier: "$$",
    notes: "Mediterranean small plates with natural wine. Williamsburg's quiet date spot.",
  },
  {
    slug: "foul-witch",
    name: "Foul Witch",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["foul witch nyc", "foul witch robertas"],
    cuisines: ["italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Roberta's team goes Italian fine dining. Quiet success.",
  },
  {
    slug: "borgo",
    name: "Borgo",
    neighborhood: "Flatiron",
    borough: "manhattan",
    search_terms: ["borgo nyc", "borgo flatiron italian"],
    cuisines: ["italian"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Italian newcomer, the calm one in the Flatiron pasta wars.",
  },
  {
    slug: "cucina-alba",
    name: "Cucina Alba",
    neighborhood: "Chelsea",
    borough: "manhattan",
    search_terms: ["cucina alba chelsea", "cucina alba quality branded"],
    cuisines: ["italian"],
    occasions: ["group-dinner", "date-night"],
    price_tier: "$$$",
    notes: "Pretty Chelsea Italian. The crowd is the dish.",
  },
  {
    slug: "penny",
    name: "Penny",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["penny nyc", "penny seafood east village"],
    cuisines: ["american"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Lyle's seafood spinoff. Oysters and natural wine, sharply done.",
  },
  {
    slug: "lords",
    name: "Lord's",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["lords nyc", "lords british east village"],
    cuisines: ["american"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "British-leaning, beef-forward, refreshingly serious.",
  },
  {
    slug: "le-pavillon",
    name: "Le Pavillon",
    neighborhood: "Midtown",
    borough: "manhattan",
    search_terms: ["le pavillon nyc", "daniel boulud le pavillon"],
    cuisines: ["french"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$$",
    notes: "Daniel Boulud seafood temple inside One Vanderbilt.",
  },
  {
    slug: "thirteen-water",
    name: "Thirteen Water",
    neighborhood: "East Village",
    borough: "manhattan",
    search_terms: ["thirteen water sushi", "thirteen water east village"],
    cuisines: ["japanese"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "$85 omakase that punches above its price.",
  },
  {
    slug: "ikigai",
    name: "Ikigai",
    neighborhood: "Fort Greene",
    borough: "brooklyn",
    search_terms: ["ikigai fort greene", "ikigai kaiseki brooklyn"],
    cuisines: ["japanese"],
    occasions: ["date-night"],
    price_tier: "$$$$",
    notes: "$185 Brooklyn kaiseki. Quietly one of NYC's best meals.",
  },
  {
    slug: "kansha",
    name: "Kansha",
    neighborhood: "Upper East Side",
    borough: "manhattan",
    search_terms: ["kansha nikkei", "kansha upper east side"],
    cuisines: ["japanese"],
    occasions: ["date-night"],
    price_tier: "$$$$",
    notes: "Nikkei (Japanese-Peruvian) in an intimate UES room.",
  },
  {
    slug: "lenlen",
    name: "LenLen",
    neighborhood: "Flatiron",
    borough: "manhattan",
    search_terms: ["lenlen thai", "lenlen flatiron"],
    cuisines: ["thai"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$",
    notes: "Modern Thai with party energy. The Flatiron's loud bet.",
  },
  {
    slug: "laccolade",
    name: "L'Accolade",
    neighborhood: "SoHo",
    borough: "manhattan",
    search_terms: ["laccolade soho", "accolade bleecker street"],
    cuisines: ["french"],
    occasions: ["date-night", "brunch"],
    price_tier: "$$$",
    notes: "Parisian bistro on Bleecker. Natural wines, seasonal menu.",
  },
  {
    slug: "dame",
    name: "Dame",
    neighborhood: "West Village",
    borough: "manhattan",
    search_terms: ["dame nyc", "dame seafood macdougal"],
    cuisines: ["american"],
    occasions: ["date-night"],
    price_tier: "$$$",
    notes: "Tiny British-ish seafood. Fish and chips that earned the line.",
  },
  {
    slug: "txikito",
    name: "Txikito",
    neighborhood: "Chelsea",
    borough: "manhattan",
    search_terms: ["txikito basque", "txikito chelsea"],
    cuisines: ["mediterranean"],
    occasions: ["date-night", "group-dinner"],
    price_tier: "$$$",
    notes: "Basque pintxos that the food critics adore.",
  },
  {
    slug: "jongro-bbq",
    name: "Jongro BBQ",
    neighborhood: "Koreatown",
    borough: "manhattan",
    search_terms: ["jongro bbq", "jongro ktown"],
    cuisines: ["korean"],
    occasions: ["group-dinner", "late-night"],
    price_tier: "$$$",
    notes: "In-house butchered Korean BBQ. Wait an hour, eat for two.",
  },
  {
    slug: "kang-ho-dong-baekjeong",
    name: "Kang Ho Dong Baekjeong",
    neighborhood: "Koreatown",
    borough: "manhattan",
    search_terms: ["kang ho dong baekjeong", "baekjeong ktown"],
    cuisines: ["korean"],
    occasions: ["group-dinner", "late-night"],
    price_tier: "$$$",
    notes: "Tabletop grill with cheesy corn moat. Loud, drunk, perfect.",
  },
  {
    slug: "gunbae",
    name: "Gunbae",
    neighborhood: "TriBeCa",
    borough: "manhattan",
    search_terms: ["gunbae tribeca", "gunbae korean bbq"],
    cuisines: ["korean"],
    occasions: ["group-dinner"],
    price_tier: "$$$",
    notes: "Karaoke rooms attached. KBBQ for the after-work crew.",
  },
  {
    slug: "insa",
    name: "Insa",
    neighborhood: "Gowanus",
    borough: "brooklyn",
    search_terms: ["insa brooklyn", "insa korean bbq gowanus"],
    cuisines: ["korean"],
    occasions: ["group-dinner", "late-night"],
    price_tier: "$$$",
    notes: "Brooklyn warehouse KBBQ with private karaoke.",
  },
  {
    slug: "the-kunjip",
    name: "The Kunjip",
    neighborhood: "Koreatown",
    borough: "manhattan",
    search_terms: ["the kunjip ktown", "kunjip 24 hour korean"],
    cuisines: ["korean"],
    occasions: ["late-night", "group-dinner"],
    price_tier: "$$",
    notes: "24-hour Koreatown standby. Soondubu at 3am.",
  },
];